name: sentra_coffee_frontend
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Mengubah versi SDK agar lebih fleksibel

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  smooth_page_indicator: ^1.1.0 # <--- INI PACKAGE YANG HARUS ADA SEKARANG!
  # Pastikan TIDAK ADA flutter_carousel_widget di sini
  uuid: ^3.0.6
  provider: ^6.0.0
  intl: ^0.19.0
  http: ^1.2.1
  shared_preferences: ^2.2.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  # Pastikan TIDAK ADA carousel_slider di sini
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/mock_menu.json
    - assets/images/logosentra.png
    - assets/images/bg_landing.png
    - assets/images/americano.png
    - assets/images/cappucino.png # Perbaiki typo, jika file gambar lo memang 'cappuccino.png'
    - assets/images/flatwhite.png
    - assets/images/latte.png
    - assets/images/logo_dana.png
    - assets/images/logo_visa_mastercard.png
    - assets/images/order_success.png

  fonts:
    - family : ReenieBeanie
      fonts:
        - asset: assets/fonts/ReenieBeanie-Regular.ttf